name: GoCD
markdown: redcarpet
future: false
navigation:
- root: Blog
  url: /blog.html
  icon: icon-comment
- root: Learn more
  url: #
  icon: icon-help-circled-1
  first-level:
    - text: Why GoCD?
      url: /learn-more/why-go.html
    - text: Subscribe to Updates
      url: /subscribe.html
    - text: Resources
      url: /community/resources.html
    - text: Help Doc
      url: http://www.go.cd/documentation/user/current/
      target: _blank
- root: Contribute
  url: #
  icon: icon-star-5
  first-level:
    - text: Get started
      url: /contribute/
    - text: Contribution Guide
      url: /contribute/contribution-guide.html
    - text: Roadmap
      url: https://github.com/gocd/gocd/milestones?direction=desc&sort=completeness&state=open
      target: _blank
    - text: CLA
      url: /contribute/cla.html
    - text: Contributors
      url: /contribute/contributors.html
    - text: Developer Guide
      url: /documentation/developer
    - text: Open Issues
      url: https://github.com/gocd/gocd/issues?page=1&state=open
      target: _blank

- root: Community
  url: #
  icon: icon-group
  first-level:
    - text: Events
      url: /community/events.html
    - text: Partners
      url: /community/partners.html
    - text: Plugins
      url: /community/plugins.html
- root: Download
  url: /download/
  icon: icon-download
